name: Pytest tests

on:
    push:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Project checkout
      uses: actions/checkout@v2 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r config/requirements.txt
        
    - name: Run tests
      run: |
        pytest

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: ./reports

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
        publish_branch: gh-pages